require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/expense_transactions', type: :request do
  # ExpenseTransaction. As you add validations to ExpenseTransaction, be sure to
  # adjust the attributes here as well.
  include Devise::Test::IntegrationHelpers
  before(:each) do
    allow(Devise.mailer).to receive(:confirmation_instructions).and_return(
      double('Mailer', deliver: true)
    )
    @user = User.create(name: 'test', email: 'test@gmail.com', password: 'test123')
    puts @user.errors.full_messages unless @user.persisted?
    @user.confirm # Confirm the user's email
    sign_in @user
    @group = Group.create(name: 'food', icon: 'https://food.png', author: @user)
  end

  let(:valid_attributes) do
    { name: 'food', amount: 100 }
  end

  let(:invalid_attributes) do
    { name: '', icon: '' }
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_expense_transaction_url
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new ExpenseTransaction' do
        expect do
          valid_attributes[:group_id] = @group.id
          post expense_transactions_url, params: { expense_transaction: valid_attributes }
        end.to change(ExpenseTransaction, :count).by(1)
      end

      it 'redirects to group ' do
        valid_attributes[:group_id] = @group.id
        post expense_transactions_url, params: { expense_transaction: valid_attributes }
        expect(response).to redirect_to(group_url(ExpenseTransaction.last.group))
      end
    end
  end
end
